//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeToPDF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeToPDF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeToPDF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeToPDF.CodeToPDF", typeof(CodeToPDF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string btnConnect {
            get {
                return ResourceManager.GetString("btnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string lblBranches {
            get {
                return ResourceManager.GetString("lblBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        internal static string lblCollections {
            get {
                return ResourceManager.GetString("lblCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string lblFolders {
            get {
                return ResourceManager.GetString("lblFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Path To Save Files.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string lblProjects {
            get {
                return ResourceManager.GetString("lblProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        internal static string lblServerName {
            get {
                return ResourceManager.GetString("lblServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No branch found..
        /// </summary>
        internal static string msgBranchNotFound {
            get {
                return ResourceManager.GetString("msgBranchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some required parameters to convert the files is null..
        /// </summary>
        internal static string msgMissingParameters {
            get {
                return ResourceManager.GetString("msgMissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No branches to show for this project. Please select another one..
        /// </summary>
        internal static string msgNoBranches {
            get {
                return ResourceManager.GetString("msgNoBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folders to show..
        /// </summary>
        internal static string msgNoFolders {
            get {
                return ResourceManager.GetString("msgNoFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folders selected..
        /// </summary>
        internal static string msgNoFoldersSelected {
            get {
                return ResourceManager.GetString("msgNoFoldersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to convert. Choose another set of folders..
        /// </summary>
        internal static string msgNoItems {
            get {
                return ResourceManager.GetString("msgNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects to show for this collection. Please select another one..
        /// </summary>
        internal static string msgNoProjects {
            get {
                return ResourceManager.GetString("msgNoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name not provided..
        /// </summary>
        internal static string msgNoServer {
            get {
                return ResourceManager.GetString("msgNoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Cancelled..
        /// </summary>
        internal static string msgProcessCancelled {
            get {
                return ResourceManager.GetString("msgProcessCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Completed..
        /// </summary>
        internal static string msgProcessCompleted {
            get {
                return ResourceManager.GetString("msgProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name not well-formed..
        /// </summary>
        internal static string msgServerUriError {
            get {
                return ResourceManager.GetString("msgServerUriError", resourceCulture);
            }
        }
    }
}
